dist: xenial
sudo: required
language: python
python:
  - 3.7

env:
  global:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
 - pipenv install --dev --deploy

script:
 - pipenv run coverage run --branch --source pyramid_heroku -m pytest pyramid_heroku
 - pipenv run coverage html
 - pipenv run coverage report --fail-under=100
 - pipenv run black pyramid_heroku/ --check
 - pipenv run mypy pyramid_heroku --ignore-missing-imports  --linecount-report typecov
 - pipenv run typecov 15 typecov/linecount.txt
