name: Update Python Packages
on:
  schedule:
    # On the second of every month
    - cron: '0 0 2 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: abatilo/actions-poetry@v2.0.0
        with:
          python_version: 3.6.0
          poetry_version: 1.0.5
          args: run bash .github/workflows/poetry-update.sh
